# -*- coding: utf-8 -*-
"""
/***************************************************************************
 kvalidator
                                 A QGIS plugin
 this plugging validates data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-09-28
        copyright            : (C) 2023 by Ruben Crespo Ceballos
        email                : ruben.crespo@bc3research.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load kvalidator class from file kvalidator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .k_validator import kvalidator
    return kvalidator(iface)
